#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
STYLES_DIR = ROOT / 'styles'
OUTPUTS = [
    ROOT / 'styles' / 'INDEX.md',
    ROOT / 'skills' / 'morph-ppt' / 'reference' / 'styles' / 'INDEX.md',
]

PALETTE_LABELS = {
    'dark': 'Dark Palette',
    'light': 'Light Palette',
    'warm': 'Warm Palette',
    'vivid': 'Vivid Palette',
    'bw': 'Black & White',
    'mixed': 'Mixed Palette',
}

HEADING_RE = re.compile(r'^#\s+(.+)\s*$')
SCENARIO_RE = re.compile(r'^-\s+\*\*(Scene|Scenario)\*\*:\s*(.+)$', re.IGNORECASE)
MOOD_RE = re.compile(r'^-\s+\*\*Mood\*\*:\s*(.+)$', re.IGNORECASE)
STYLE_DIR_RE = re.compile(r'^[a-z]+--[a-z0-9-]+$')


def clean_title(raw: str) -> str:
    text = raw.replace('—', '--')
    if '--' in text:
        text = text.split('--', maxsplit=1)[1].strip()
    text = re.sub(r'^(S\d+|\d+[-_A-Za-z0-9]*)\s+', '', text).strip()
    return text or raw.strip()


def parse_style_metadata(style_md: Path) -> tuple[str, str, str]:
    heading = style_md.parent.name
    scenario = '-'
    mood = '-'

    for line in style_md.read_text(encoding='utf-8').splitlines():
        if heading == style_md.parent.name:
            h = HEADING_RE.match(line)
            if h:
                heading = clean_title(h.group(1).strip())
                continue

        s = SCENARIO_RE.match(line)
        if s and scenario == '-':
            scenario = s.group(2).strip()
            continue

        m = MOOD_RE.match(line)
        if m and mood == '-':
            mood = m.group(1).strip()

    return heading, scenario, mood


def iter_styles() -> Iterable[Path]:
    for path in sorted(STYLES_DIR.iterdir()):
        if path.is_dir() and STYLE_DIR_RE.match(path.name):
            yield path


def bool_mark(flag: bool) -> str:
    return 'Yes' if flag else 'No'


def build_index() -> str:
    rows_by_palette: dict[str, list[dict[str, str]]] = {}
    total = 0
    missing_script: list[str] = []
    missing_pptx: list[str] = []

    for style_dir in iter_styles():
        total += 1
        slug = style_dir.name
        palette = slug.split('--', maxsplit=1)[0] if '--' in slug else 'other'
        style_md = style_dir / 'style.md'

        title = slug
        scenario = '-'
        mood = '-'
        if style_md.exists():
            title, scenario, mood = parse_style_metadata(style_md)

        has_script = (style_dir / 'build.sh').exists() or (style_dir / 'build.py').exists()
        has_pptx = any(style_dir.glob('*.pptx'))

        if not has_script:
            missing_script.append(slug)
        if not has_pptx:
            missing_pptx.append(slug)

        rows_by_palette.setdefault(palette, []).append(
            {
                'slug': slug,
                'title': title,
                'scenario': scenario,
                'mood': mood,
                'script': bool_mark(has_script),
                'pptx': bool_mark(has_pptx),
            },
        )

    lines: list[str] = []
    lines.append('# Style Index')
    lines.append('')
    lines.append('This file is auto-generated by `python3 tools/generate_style_index.py`.')
    lines.append('')
    lines.append('## Summary')
    lines.append('')
    lines.append(f'- Total templates: **{total}**')
    lines.append(f'- Missing script (`build.sh` or `build.py`): **{len(missing_script)}**')
    lines.append(f'- Missing `.pptx` sample: **{len(missing_pptx)}**')
    lines.append('')

    if missing_script:
        lines.append('### Missing Script')
        lines.append('')
        for slug in missing_script:
            lines.append(f'- `{slug}`')
        lines.append('')

    if missing_pptx:
        lines.append('### Missing PPTX')
        lines.append('')
        for slug in missing_pptx:
            lines.append(f'- `{slug}`')
        lines.append('')

    ordered_palettes = list(PALETTE_LABELS.keys()) + sorted(
        key for key in rows_by_palette.keys() if key not in PALETTE_LABELS
    )

    for palette in ordered_palettes:
        rows = rows_by_palette.get(palette)
        if not rows:
            continue

        label = PALETTE_LABELS.get(palette, f'{palette} Palette')
        lines.append(f'## {label} (`{palette}`)')
        lines.append('')
        lines.append('| Directory | Style Name | Scenario | Mood | Script | PPTX |')
        lines.append('| --- | --- | --- | --- | --- | --- |')
        for row in rows:
            scenario = row['scenario'].replace('|', '\\|')
            mood = row['mood'].replace('|', '\\|')
            lines.append(
                f"| `{row['slug']}` | {row['title']} | {scenario} | {mood} | {row['script']} | {row['pptx']} |",
            )
        lines.append('')

    return '\n'.join(lines)


def main() -> None:
    content = build_index()
    for output in OUTPUTS:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content + '\n', encoding='utf-8')
        print(f'updated: {output.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
